Проверка рабочего процесса
htmlacademy-javascript/2109415-keksobooking-26 pull request #1
Opened 2022-06-01 14:08 UTC by ivmerk

---
:mortar_board: [Проверка рабочего процесса](https://up.htmlacademy.ru/javascript/26/user/2109415/tasks/5)

:boom: https://htmlacademy-javascript.github.io/2109415-keksobooking-26/1/

2022-06-01 14:29 UTC, ivmerk commented
Добавляем имя наставника.

2022-06-01 18:08 UTC, Dima-Dim requested changes

2022-06-01 18:08 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Отредактируй, пожалуйста, строку Наставник чтобы было по аналогии со строкой Студент. Для этого нужно добавить ссылку на мой профиль https://htmlacademy.ru/profile/dima

2022-06-01 18:29 UTC, ivmerk commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Исправил

2022-06-02 07:11 UTC, Dima-Dim approved these changes

2022-06-02 07:11 UTC, merged