creation of the object
htmlacademy-javascript/2109415-keksobooking-26 pull request #3
Opened 2022-06-10 06:45 UTC by ivmerk

2022-06-11 05:08 UTC, Dima-Dim requested changes
Не забывай обращать внимание на замечания линтера.

2022-06-11 05:08 UTC, Dima-Dim commented on js/main.js
> +  const arr = input.slice();
https://up.htmlacademy.ru/javascript/26/criteries#b5 и для других массивов тоже.

2022-06-11 05:08 UTC, Dima-Dim commented on js/main.js
> +      lat: getRandomNumber (35.65, 35.7, 5),
https://up.htmlacademy.ru/javascript/26/criteries#d19

2022-06-13 12:38 UTC, ivmerk reviewed
correction

2022-06-14 02:58 UTC, Dima-Dim requested changes
Один из массивов всё ещё называется arr, а ещё один result, т.е. оба они нарушают критерий про именование массивов. Плюс появились замечания от линтера, которые тоже нужно учитывать.

2022-06-14 02:58 UTC, Dima-Dim commented
После последнего коммита вижу что замечаний от линтера уже нет. Это хорошо, но неймин всё ещё нужно поправить.

2022-06-14 16:53 UTC, merged